---
version: "2"

services:
  db:
    image: camptocamp/geomapfish-test-db:latest
    environment:
      - POSTGRES_USER=www-data
      - POSTGRES_PASSWORD=www-data
      - POSTGRES_DB=geomapfish_tests

  qgisserver-tests:
    build: .
    image: camptocamp/geomapfish-qgisserver-tests:qgis3.4
    volumes:
      - $PWD/acceptance_tests:/acceptance_tests  # dev
      - $PWD/geomapfish_qgisserver:/var/www/plugins/geomapfish_qgisserver  #dev
    links:
      - db
    command: py.test --verbose --color=yes --cov=geomapfish_qgisserver /acceptance_tests
